# Generated by go2rpm 1.9.0
%bcond_with check

# https://github.com/josephspurrier/goversioninfo
%global goipath         github.com/josephspurrier/goversioninfo
Version:                1.4.0

%gometa

%global common_description %{expand:
Golang Microsoft Windows File Properties/Version Info and Icon Resource
Generator.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Golang Microsoft Windows File Properties/Version Info and Icon Resource Generator

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(github.com/akavel/rsrc/binutil)
BuildRequires:  golang(github.com/akavel/rsrc/coff)
BuildRequires:  golang(github.com/akavel/rsrc/ico)
%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

Provides: goversioninfo

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Fri May 26 2023 Christian Glombek <cglombek@redhat.com> - 1.4.0-1
- Initial package
